### ISSUE TITLE
As a student, I want to request the creation for a new course to the system, so that I can sell items related to this course

### ISSUE THREAD

**Issue by JosephSaliba01** [IBGA/UniTrade#25]
A request to create/edit/remove a course for a university is accepted or denied my moderator students of the appropriate university
- [x] #43
- [x] #44
- [x] #45
- [x] #46

**Comment by Charles-Spencer-Blancas** [comment]
Moved to Sprint B because it needs multiple other Sprint B features to be done as well (like Moderation Role)
